import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';

// Importar iconos sólidos (Solid)
import {
    faHouse,
    faClipboardCheck,
    faBox,
    faUsers,
    faChartLine,
    faGear,
    faBars,
    faBell,
    faSun,
    faMoon,
    faRightFromBracket,
    faXmark,
    faCalendar,
    faCircleCheck,
    faClock,
    faRotateLeft,
    faUser,
    faMagnifyingGlass,
    faCircleExclamation,
    faLocationDot,
    faChevronLeft,
    faChartPie,
    faInbox,
    faTruck,
    faTriangleExclamation,
    faCheck,
    faChevronDown,
    faArrowRight,
    faArrowLeft,
    faPlus,
    faMinus,
    faPencil,
    faTrash,
    faEye,
    faEyeSlash,
    faLock,
    faEnvelope,
    faPhone,
    faMapLocationDot,
    faBarcode,
    faCamera,
    faQrcode,
    faSignature,
    faFileInvoice,
    faTruckFast,
    faRoute,
    faWarehouse,
    faClipboardList,
    faBoxesStacked,
    faIdCard,
    faMoneyBill,
    faPercent,
    faCalculator,
    faFilter,
    faSort,
    faSortUp,
    faSortDown,
    faSearch,
    faTimes,
    faInfoCircle,
    faQuestionCircle,
    faExclamationTriangle,
    faCheckCircle,
    faTimesCircle,
    faArrowUp,
    faArrowDown,
    faUpload,
    faDownload,
    faPrint,
    faFile,
    faFilePdf,
    faFileExcel,
    faFileCsv,
    faCopy,
    faPaste,
    faUndo,
    faRedo,
    faRefresh,
    faSpinner,
    faCircleNotch,
    faHome,
    faDashboard,
    faTachometerAlt,
    faCog,
    faWrench,
    faUserCircle,
    faUserPlus,
    faUserMinus,
    faUserEdit,
    faSignOutAlt,
    faSignInAlt,
    faKey,
    faUnlock,
    faShieldAlt,
    faHistory,
    faClockRotateLeft,
    faTableColumns,
} from '@fortawesome/free-solid-svg-icons';

// Importar iconos regulares (Regular)
import {
    faCircle as faCircleRegular,
    faCalendar as faCalendarRegular,
    faClock as faClockRegular,
    faEnvelope as faEnvelopeRegular,
    faFile as faFileRegular,
    faFolder as faFolderRegular,
    faFolderOpen as faFolderOpenRegular,
    faComment as faCommentRegular,
    faComments as faCommentsRegular,
    faThumbsUp as faThumbsUpRegular,
    faThumbsDown as faThumbsDownRegular,
    faStar as faStarRegular,
    faBookmark as faBookmarkRegular,
    faHeart as faHeartRegular,
    faCheckCircle as faCheckCircleRegular,
    faTimesCircle as faTimesCircleRegular,
} from '@fortawesome/free-regular-svg-icons';

// Agregar iconos a la librería
library.add(
    // Solid
    faHouse,
    faClipboardCheck,
    faBox,
    faUsers,
    faChartLine,
    faGear,
    faBars,
    faBell,
    faSun,
    faMoon,
    faRightFromBracket,
    faXmark,
    faCalendar,
    faCircleCheck,
    faClock,
    faRotateLeft,
    faUser,
    faMagnifyingGlass,
    faCircleExclamation,
    faLocationDot,
    faChevronLeft,
    faChartPie,
    faInbox,
    faTruck,
    faTriangleExclamation,
    faCheck,
    faChevronDown,
    faArrowRight,
    faArrowLeft,
    faPlus,
    faMinus,
    faPencil,
    faTrash,
    faEye,
    faEyeSlash,
    faLock,
    faEnvelope,
    faPhone,
    faMapLocationDot,
    faBarcode,
    faCamera,
    faQrcode,
    faSignature,
    faFileInvoice,
    faTruckFast,
    faRoute,
    faWarehouse,
    faClipboardList,
    faBoxesStacked,
    faIdCard,
    faMoneyBill,
    faPercent,
    faCalculator,
    faFilter,
    faSort,
    faSortUp,
    faSortDown,
    faSearch,
    faTimes,
    faInfoCircle,
    faQuestionCircle,
    faExclamationTriangle,
    faCheckCircle,
    faTimesCircle,
    faArrowUp,
    faArrowDown,
    faUpload,
    faDownload,
    faPrint,
    faFile,
    faFilePdf,
    faFileExcel,
    faFileCsv,
    faCopy,
    faPaste,
    faUndo,
    faRedo,
    faRefresh,
    faSpinner,
    faCircleNotch,
    faHome,
    faDashboard,
    faTachometerAlt,
    faCog,
    faWrench,
    faUserCircle,
    faUserPlus,
    faUserMinus,
    faUserEdit,
    faSignOutAlt,
    faSignInAlt,
    faKey,
    faUnlock,
    faShieldAlt,
    faHistory,
    faClockRotateLeft,
    faTableColumns,
    // Regular
    faCircleRegular,
    faCalendarRegular,
    faClockRegular,
    faEnvelopeRegular,
    faFileRegular,
    faFolderRegular,
    faFolderOpenRegular,
    faCommentRegular,
    faCommentsRegular,
    faThumbsUpRegular,
    faThumbsDownRegular,
    faStarRegular,
    faBookmarkRegular,
    faHeartRegular,
    faCheckCircleRegular,
    faTimesCircleRegular
);

export { FontAwesomeIcon };

// Exportar un plugin para Vue
export default {
    install(app) {
        app.component('FontAwesomeIcon', FontAwesomeIcon);
    }
};
